### ISSUE TITLE
Question: Can we do the same with any static library or pods?

### ISSUE THREAD

**Issue by TofPlay** [akashivskyy/GoogleAnalytics-Framework#11]
Hi,
Really interesting project 👍 😄
I have 3 pods that I want to use with Carthage. 
Can I also convert them like you did with GoogleAnalytics?

The pods that I want to convert to Carthage:
- [Zopim Mobile SDK for iOS](https://cocoapods.org/pods/ZDCChat)
- [Fabric](https://cocoapods.org/pods/Fabric)
- [Crashlytics](https://fabric.io/kits/ios/crashlytics/install)

Or better do you know a tool that would automatically convert a CocoaPods component to a Framework compatible with Carthage? ( not written in Ruby... please 🙏  )

**Comment by akashivskyy** [comment]
Hi, sorry for a delayed response (I must have missed the notification).

Of course, you can convert them as I did, but, unfortunately, there is no tool that does this automatically. 😔 You can do this manually, by creating and exposing a framework target and linking it against the closed-source static library of your choice.
