### ISSUE TITLE
Use of unresolved identifier 'GGLContext' in AppDelegate.swift

### ISSUE THREAD

**Issue by pollax** [akashivskyy/GoogleAnalytics-Framework#12]
Hi,
I think I'm doing something wrong when adding this framework to my iOS project, but I can't figure out what.

I've added it to my Cartfile, I've done `carthage bootstrap` and then I added the framework according to https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos
I do this in my AppDelegate.swift:
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: 
[UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    // ...  
    // Google analytics   
    var configureError: NSError?  
    GGLContext.sharedInstance().configureWithError(&configureError)  
    assert(configureError == nil, "Error configuring Google services: \(configureError)")  
    // ...
}
```
but then I get the error in the title: `Use of unresolved identifier 'GGLContext' in AppDelegate.swift`
Do you have any gut feeling/idea what could be wrong? Do I need to add the xconfigs framework that this framework depends on, according to https://github.com/Carthage/Carthage#nested-dependencies?

**Comment by akashivskyy** [comment]
That's because there is no such class as `GGLContext` in `GoogleAnalytics.framework`. 🙂 

>Do I need to add the xconfigs framework that this framework depends on, according to https://github.com/Carthage/Carthage#nested-dependencies?

No, it is a private dependency and it is needed to compile the framework when running `carthage bootstrap.
