### ISSUE TITLE
Getting Crash in [GAIDataStore fetchHitsWithLimit:error:]

### ISSUE THREAD

**Issue by abhishek33u** [akashivskyy/GoogleAnalytics-Framework#15]
Hi Team,

I am getting a crash in google analytics. The stack trace of the crash report is attached below. I have checked my code and i didn't find any issue from my side. Kindly help me to debug this because it's affecting my 463k users.

# Date: 2019-10-25T12:48:00Z
# OS Version: 12.3.1 (16F203)
# Device: iPhone 7
# RAM Free: 2.8%
# Disk Free: 32.7%

#5. Crashed: GAIThread
0  libsqlite3.dylib               0x1e67ff098 sqlite3_finalize + 24708
1  libsqlite3.dylib               0x1e67fd974 sqlite3_finalize + 18784
2  libsqlite3.dylib               0x1e67fd974 sqlite3_finalize + 18784
3  libsqlite3.dylib               0x1e67fd240 sqlite3_finalize + 16940
4  libsqlite3.dylib               0x1e67fb714 sqlite3_finalize + 9984
5  libsqlite3.dylib               0x1e67fab54 sqlite3_finalize + 6976
6  libsqlite3.dylib               0x1e6819f10 sqlite3_step + 13664
7  libsqlite3.dylib               0x1e6816b6c sqlite3_step + 444
8  CoreData                       0x1e8fd75e4 _execute + 156
9  CoreData                       0x1e8e3df4c -[NSSQLiteConnection execute] + 2780
10 CoreData                       0x1e8fed20c newFetchedRowsForFetchPlan_MT + 812
11 CoreData                       0x1e90881a0 _executeFetchRequest + 68
12 CoreData                       0x1e8e40d80 -[NSSQLFetchRequestContext executeRequestCore:] + 36
13 CoreData                       0x1e8e3744c -[NSSQLStoreRequestContext executeRequestUsingConnection:] + 252
14 CoreData                       0x1e8f97074 __52-[NSSQLDefaultConnectionManager handleStoreRequest:]_block_invoke + 84
15 libdispatch.dylib              0x1e5e217d4 _dispatch_client_callout + 16
16 libdispatch.dylib              0x1e5dcfc18 _dispatch_lane_barrier_sync_invoke_and_complete + 56
17 CoreData                       0x1e8e372b4 -[NSSQLDefaultConnectionManager handleStoreRequest:] + 264
18 CoreData                       0x1e8e37168 -[NSSQLCoreDispatchManager routeStoreRequest:] + 264
19 CoreData                       0x1e8e36f24 -[NSSQLCore dispatchRequest:withRetries:] + 260
20 CoreData                       0x1e8e40c74 -[NSSQLCore processFetchRequest:inContext:] + 108
21 CoreData                       0x1e8e37df8 -[NSSQLCore executeRequest:withContext:error:] + 492
22 CoreData                       0x1e8fa0f48 __65-[NSPersistentStoreCoordinator executeRequest:withContext:error:]_block_invoke + 1712
23 CoreData                       0x1e8e36d14 -[NSPersistentStoreCoordinator _routeHeavyweightBlock:] + 240
24 CoreData                       0x1e8e3799c -[NSPersistentStoreCoordinator executeRequest:withContext:error:] + 844
25 CoreData                       0x1e8e3fe34 -[NSManagedObjectContext executeFetchRequest:error:] + 896
26 jarvis_common_ios              0x10b7f4eb8 __41-[GAIDataStore fetchHitsWithLimit:error:]_block_invoke + 204
27 jarvis_common_ios              0x10b7f3474 -[GAIDataStore performBlockAndWait:withError:] + 380
28 jarvis_common_ios              0x10b7f4dc4 -[GAIDataStore fetchHitsWithLimit:error:] + 92
29 jarvis_common_ios              0x10b8020b0 -[GAIBatchingDispatcher nextPendingHits] + 416
30 jarvis_common_ios              0x10b801734 -[GAIBatchingDispatcher hitsForDispatch] + 64
31 jarvis_common_ios              0x10b802ca8 -[GAIBatchingDispatcher dispatchWithCompletionHandler:] + 360
32 Foundation                     0x1e6e688a4 __NSFireTimer + 84
33 CoreFoundation                 0x1e6373650 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
34 CoreFoundation                 0x1e6373380 __CFRunLoopDoTimer + 864
35 CoreFoundation                 0x1e6372bb4 __CFRunLoopDoTimers + 248
36 CoreFoundation                 0x1e636db04 __CFRunLoopRun + 1844
37 CoreFoundation                 0x1e636d0b0 CFRunLoopRunSpecific + 436
38 Foundation                     0x1e6d3afac -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 300
39 Foundation                     0x1e6d7646c -[NSRunLoop(NSRunLoop) run] + 88
40 jarvis_common_ios              0x10b7f1338 +[GAI threadMain:] + 64
41 Foundation                     0x1e6e676a4 __NSThread__start__ + 984
42 libsystem_pthread.dylib        0x1e60002c0 _pthread_body + 128
43 libsystem_pthread.dylib        0x1e6000220 _pthread_start + 44
44 libsystem_pthread.dylib        0x1e6003cdc thread_start + 4

 
<img width="1382" alt="Screenshot 2019-10-25 at 6 30 08 PM" src="https://user-images.githubusercontent.com/25417648/67573660-7db87700-f756-11e9-82c0-40e851e0683b.png">

**Comment by akashivskyy** [comment]
Hi there! I don't work for Google and I don't work on Google Analytics SDK. This project just repackages [Google Analytics binary](https://developers.google.com/analytics/devguides/collection/ios/v3/) in a format recognizable by Carthage. I don't even use the framework myself anymore.

I recommend you [contact Google's support](https://developers.google.com/analytics/devguides/collection/ios/v3/help) as they are the ones that can actually fix the issue.

Have a nice day! 🙌

**Comment by abhishek33u** [comment]
Thanks @akashivskyy
