### ISSUE TITLE
Always get this error, after a successful build. Verbose output gives nothing extra.

### ISSUE THREAD

**Issue by ryanbooker** [akashivskyy/GoogleAnalytics-Framework#2]
With the latest Carthage from Brew, I always get this error: 

```
Failed to read file or folder at /Users/blah/Library/Developer/Xcode/DerivedData/Google_Analytics-aamtibhbwnbjfbaygpbizlinlquw/Build/Products/Release-iphoneos/GoogleAnalytics.framework
```

The build succeeds and there is a framework and dsym in that build folder. 

Any ideas?

**Comment by akashivskyy** [comment]
Errors might have been caused by unsupported Bitcode settings. Please check now with version 3.15.

**Comment by akashivskyy** [comment]
Closing this as installation errors can no longer be reproduced.
