### ISSUE TITLE
Have to disable bitcode in my project

### ISSUE THREAD

**Issue by patricks** [akashivskyy/GoogleAnalytics-Framework#5]
I thought since Google Analytics 3.15 i can enable bitcode? If I use this carthage framework, I get an error, if I have enabled bitcode. Is this correct? Or is it possible to enable bitcode?

**Comment by akashivskyy** [comment]
Hi @patricks, could you clarify what exact error are you getting and where (or when) does this error appear?

**Comment by patricks** [comment]
Hi @akashivskyy,

I get the error if I try to build my project, which now includes the google analytics framework.

I get the following error:
```
.../Carthage/Build/iOS/GoogleAnalytics.framework/GoogleAnalytics' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
```

This happens if I try to build the project vor my device

**Comment by akashivskyy** [comment]
@patricks Please check 76e59ebb33fac7f7951acced1e423c36ff4aaba9. Does this error still occur? You can check out the latest `master` version using:

```none
github "akashivskyy/GoogleAnalytics-Framework" "master"
```

If you confirm the issue is resolved, I will retag `3.15` to 76e59ebb33fac7f7951acced1e423c36ff4aaba9.

**Comment by patricks** [comment]
@akashivskyy yes this fixes the problem thx!

**Comment by akashivskyy** [comment]
Great! `3.15` has been changed to point to 76e59ebb33fac7f7951acced1e423c36ff4aaba9. You can now use version numbers as before. Please remember to `carthage update`!

```none
github "akashivskyy/GoogleAnalytics-Framework" ~> 3.15
```
