### ISSUE TITLE
Google Tag Manager not included

### ISSUE THREAD

**Issue by volodymyr-ivanyshyn-ja** [akashivskyy/GoogleAnalytics-Framework#7]
Google Tag Manager is provided with Google Analytics lib. To enable it we should add corresponding header files from Google Analytics SDK:
TAGContainer.h
TAGContainerOpener.h
TAGDataLayer.h
TAGLogger.h
TAGManager.h

Because you distributes the framework through Carthage, it takes extra work to add these headers each time after the framework is being cloned.

**Comment by akashivskyy** [comment]
Right, must've missed that. I'll add those to the framework and retag the v3.15 tomorrow.

**Comment by akashivskyy** [comment]
Done, please `carthage update`. 😉
