### ISSUE TITLE
Configuration via Configfile?

### ISSUE THREAD

**Issue by Hendrik44** [akashivskyy/GoogleAnalytics-Framework#8]
When i want to configure GA with the code snippet from google 
```
var configureError:NSError?
GGLContext.sharedInstance().configureWithError(&configureError)
assert(configureError == nil, "Error configuring Google services: \(configureError)")
```
i get an error that the GGLContext is not found. 

Is the configuration via configfile not support for this framework?

**Comment by akashivskyy** [comment]
Could you paste the full error message with `userInfo`?

**Comment by DigitalD1982** [comment]
Having the same issue, this is a compile time error though so you can't access userInfo. Not sure where GGLContext is defined but it seems that importing the GoogleAnalytics framework is not enough.

**Comment by akashivskyy** [comment]
@DigitalD1982 Can you paste a full compile log?

**Comment by klemenkosir** [comment]
It seems you dont need GGLContext part, you only need this GAI.sharedInstance().trackerWithTrackingId("YOUR TRACKING ID")

**Comment by Hendrik44** [comment]
@klemenkosir yes i can use it but than i get an "GoogleAnalytics 3.16 +[GAITrackerModel initialize] (GAITrackerModel.m:88): idfa class missing, won't collect idfa" message and tracking will not work

@DigitalD1982 
![screen shot 2016-09-10 at 22 16 46](https://cloud.githubusercontent.com/assets/4581596/18413308/52d67364-77a4-11e6-81a3-697da577fe89.png) i can't use GGLContext because it not known

**Comment by klemenkosir** [comment]
@Hendrik44 weird because it works fine for me without any error. 

I put this in the AppDelegate
`GAI.sharedInstance().trackerWithTrackingId("UA-00000000-0")
GAI.sharedInstance().trackUncaughtExceptions = true`

and then this in my ViewController
`let tracker = GAI.sharedInstance().defaultTracker
		tracker.set(kGAIScreenName, value: "screen name")
		
		let builder = GAIDictionaryBuilder.createScreenView()
		tracker.send(builder.build() as [NSObject : AnyObject])`

and it works just fine :D

**Comment by Hendrik44** [comment]
Thanks für you help.
After many tries and different configs now it works. Issue can be closed

**Comment by elsurudo** [comment]
@Hendrik44 I am having the same issue as you (`GGLContext` isn't found). Ca you let me know how you fixed this?

**Comment by Hendrik44** [comment]
Im using the following code and all works fine and now no error appear:
```swift
let gai = GAI.sharedInstance()
gai?.trackUncaughtExceptions = true  // report uncaught exceptions   
gai?.defaultTracker = gai?.tracker(withTrackingId: "UA-123456")   
```

**Comment by elsurudo** [comment]
I see. But still, I'd like to use the configuration file if possible, as it contains other info.

Example:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>TRACKING_ID</key>
	<string>***redacted***</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>***redacted***</string>
	<key>PROJECT_ID</key>
	<string>***redacted***</string>
	<key>IS_ADS_ENABLED</key>
	<false/>
	<key>IS_ANALYTICS_ENABLED</key>
	<true/>
	<key>IS_APPINVITE_ENABLED</key>
	<false/>
	<key>IS_GCM_ENABLED</key>
	<false/>
	<key>IS_SIGNIN_ENABLED</key>
	<false/>
	<key>GOOGLE_APP_ID</key>
	<string>***redacted***</string>
</dict>
</plist>
```

Specifically, it contains the Google App ID as well, which means my events will map to a specific app.

With your solution, do you get this mapping as well? how do events appear in the GA dashboard?

**Comment by klemenkosir** [comment]
@elsurudo Why don't you just try to use Firebase? ...it has analytics :D

**Comment by elsurudo** [comment]
Well, we already use GA for our web properties (which this app is associated with). I’d rather all of it be in one place. Any specific reason to use Firebase for analytics? I know Firebase from the DB/JS stuff.

**Comment by klemenkosir** [comment]
As fas as i know it has all the essential stuff that GA has, plus it also supports push notifications for ios/android. And for basic analytics you just have to call FIRApp.configure() and thats it :D, also maybe there is a way to connect GA and firebase since both are from google now :D

**Comment by elsurudo** [comment]
Ahh. Thanks for the suggestion, but I think I’d like to avoid another dependency for now. I’ll look into Firebase anyhow, out of curiosity.

**Comment by klemenkosir** [comment]
if it helps ...here's my code for GA before switching to Firebase

		GAI.sharedInstance().trackerWithTrackingId("UA-XXXXXXX-1")
		GAI.sharedInstance().trackUncaughtExceptions = true
		let tracker = GAI.sharedInstance().defaultTracker
		tracker.set(kGAIScreenName, value: "some screen name")
		let builder = GAIDictionaryBuilder.createScreenView()
		tracker.send(builder.build() as [NSObject : AnyObject])
