### ISSUE TITLE
Google Analytics V3.17

### ISSUE THREAD

**Issue by tuxtux59** [akashivskyy/GoogleAnalytics-Framework#9]
Hello,

I'm wondering if an update to GoogleAnalytics v3.17 is planned because some conflitcs with IOS10 arrival prevent all send data from mobile to analytics.

**Comment by akashivskyy** [comment]
Yup, will update ASAP.

**Comment by tuxtux59** [comment]
Thanks :)

**Comment by akashivskyy** [comment]
Done, please do `carthage update`. 🙂
